import type { Tables } from '@/lib/database.types'
import type { FormField } from '@/lib/types'

type SectorRow = Tables<'sectors'>

export interface SectorContentEntry {
  key: 'medical' | 'industrie' | 'technology' | 'academia'
  order: number
  name: string
  nameAr: string
  shortDescription: string
  shortDescriptionAr: string
  heroDescription: string
  heroDescriptionAr: string
  overviewTitle: string
  overviewTitleAr: string
  scope: string
  scopeAr: string
  professionalLink: string
  professionalLinkAr: string
  benefit: string
  benefitAr: string
  registrationIntro: string
  registrationIntroAr: string
  accent: string
}

const sectorEntries: SectorContentEntry[] = [
  {
    key: 'medical',
    order: 1,
    name: 'JAZ Medical',
    nameAr: 'جاز الطبية',
    shortDescription: 'Healthcare, life sciences, and medical innovation connected through global medical congresses and exhibitions.',
    shortDescriptionAr: 'الرعاية الصحية، العلوم الحياتية، والابتكار الطبي ضمن منصة ربط للمؤتمرات والمعارض الطبية الدولية.',
    heroDescription: 'A specialized gateway connecting Iraqi healthcare professionals and institutions with international medical congresses and exhibitions.',
    heroDescriptionAr: 'بوابة متخصصة لربط الكوادر الصحية والمؤسسات الطبية العراقية بالمؤتمرات والمعارض العالمية.',
    overviewTitle: 'Healthcare, life sciences, and medical innovation.',
    overviewTitleAr: 'الرعاية الصحية والعلوم الحياتية والابتكار الطبي.',
    scope: 'Healthcare, life sciences, and medical innovation.',
    scopeAr: 'الرعاية الصحية، العلوم الحياتية، والابتكار الطبي.',
    professionalLink: 'Specialized in managing international medical gatherings and facilitating access for healthcare professionals and institutions to global medical congresses.',
    professionalLinkAr: 'تخصص في إدارة المحافل الطبية الدولية وتسهيل وصول الكوادر الصحية والمؤسسات إلى المؤتمرات والمعارض العالمية (Medical Congresses).',
    benefit: 'Enables knowledge exchange with international research centers, access to the latest treatment technologies, and direct connections with experts and manufacturers.',
    benefitAr: 'تحقيق التبادل المعرفي مع المراكز البحثية الدولية، واكتساب أحدث التقنيات العلاجية، وتطوير القطاع الصحي عبر قنوات التواصل المباشر مع الخبراء والمصنعين.',
    registrationIntro: 'If you represent a healthcare institution, medical team, or research body and want to connect with us about this sector, please complete the form below.',
    registrationIntroAr: 'إذا كنتم تمثلون مؤسسة صحية أو فريقاً طبياً أو جهة بحثية وترغبون بالتواصل معنا بخصوص هذا القطاع، يمكنكم تعبئة النموذج التالي.',
    accent: '#b42318',
  },
  {
    key: 'industrie',
    order: 2,
    name: 'JAZ Industrie',
    nameAr: 'جاز الصناعية',
    shortDescription: 'Manufacturing, international trade, and supply chains linked to major industrial exhibitions and business delegations.',
    shortDescriptionAr: 'التصنيع، التجارة الدولية، وسلاسل التوريد عبر ربط الشركات المحلية بالمنصات الصناعية الدولية.',
    heroDescription: 'A strategic bridge integrating the local industrial sector into major trade fairs and industrial delegations.',
    heroDescriptionAr: 'حلقة وصل استراتيجية لدمج القطاع الصناعي المحلي في المعارض التجارية والوفود الصناعية الكبرى.',
    overviewTitle: 'Manufacturing, international trade, and supply chains.',
    overviewTitleAr: 'التصنيع والتجارة الدولية وسلاسل التوريد.',
    scope: 'Manufacturing, international trade, and supply chains.',
    scopeAr: 'التصنيع، التجارة الدولية، وسلاسل التوريد.',
    professionalLink: 'Acts as a direct connector for integrating local industry into international trade exhibitions and large-scale industrial delegations.',
    professionalLinkAr: 'حلقة وصل لدمج القطاع الصناعي المحلي في المعارض التجارية والوفود الصناعية الكبرى.',
    benefit: 'Supports industrial partnerships, facilitates access to manufacturing technology, and opens new markets through direct B2B engagement on global industrial platforms.',
    benefitAr: 'توطين الشراكات الصناعية، وتسهيل استيراد التكنولوجيا التصنيعية، وفتح أسواق جديدة للشركات من خلال اللقاءات المباشرة (B2B) داخل المنصات الصناعية العالمية.',
    registrationIntro: 'If your inquiry concerns an industrial delegation, commercial partnership, or participation in a specialized exhibition, please submit it through the form below.',
    registrationIntroAr: 'إذا كان استفساركم يتعلق بوفد صناعي أو شراكة تجارية أو مشاركة في معرض متخصص، يمكنكم إرسال الطلب من خلال النموذج التالي.',
    accent: '#9a3412',
  },
  {
    key: 'technology',
    order: 3,
    name: 'JAZ Technology',
    nameAr: 'جاز التكنولوجية',
    shortDescription: 'Digital transformation, information technology, and communications for startups and tech companies seeking global exposure.',
    shortDescriptionAr: 'التحول الرقمي، تكنولوجيا المعلومات، والاتصالات لربط رواد الأعمال والشركات التقنية بالقمم العالمية.',
    heroDescription: 'A specialized unit connecting entrepreneurs and technology companies with major tech summits and digital innovation exhibitions.',
    heroDescriptionAr: 'وحدة متخصصة في ربط رواد الأعمال والشركات التقنية بالقمم التكنولوجية ومعارض الابتكار الرقمي.',
    overviewTitle: 'Digital transformation, information technology, and communications.',
    overviewTitleAr: 'التحول الرقمي وتكنولوجيا المعلومات والاتصالات.',
    scope: 'Digital transformation, information technology, and communications.',
    scopeAr: 'التحول الرقمي، تكنولوجيا المعلومات، والاتصالات.',
    professionalLink: 'Dedicated to linking entrepreneurs and tech companies with technology summits and digital innovation exhibitions.',
    professionalLinkAr: 'وحدة متخصصة في ربط رواد الأعمال والشركات التقنية بالقمم التكنولوجية ومعارض الابتكار الرقمي.',
    benefit: 'Facilitates access to modern technological infrastructure and supports digital entrepreneurship through exposure to global innovators.',
    benefitAr: 'تيسير الوصول إلى البنى التحتية التكنولوجية الحديثة، ودعم ريادة الأعمال الرقمية عبر الاحتكاك بالشركات العالمية المبتكرة في بيئات المعارض التكنولوجية.',
    registrationIntro: 'If you are seeking technical collaboration, representation at a technology summit, or a digital transformation partnership, use the form below.',
    registrationIntroAr: 'إذا كنتم تبحثون عن فرص تعاون تقني أو تمثيل في قمة تكنولوجية أو شراكة تحول رقمي، استخدموا النموذج التالي.',
    accent: '#0f766e',
  },
  {
    key: 'academia',
    order: 4,
    name: 'JAZ Academia',
    nameAr: 'جاز الأكاديمية',
    shortDescription: 'Higher education, scientific research, and professional development through academic and institutional exchange.',
    shortDescriptionAr: 'التعليم العالي، البحث العلمي، والتطوير المهني عبر ربط الجامعات والمؤسسات التعليمية بالمنصات الدولية.',
    heroDescription: 'Strengthens the relationship between academia and industry through scientific forums and research conferences.',
    heroDescriptionAr: 'تعزيز العلاقة بين الأوساط الأكاديمية وقطاع الأعمال من خلال المنتديات العلمية والمؤتمرات البحثية.',
    overviewTitle: 'Higher education, scientific research, and professional development.',
    overviewTitleAr: 'التعليم العالي والبحث العلمي والتطوير المهني.',
    scope: 'Higher education, scientific research, and professional development.',
    scopeAr: 'التعليم العالي، البحث العلمي، والتطوير المهني.',
    professionalLink: 'Enhances collaboration between academic communities and the business sector through scientific forums and research conferences.',
    professionalLinkAr: 'تعزيز العلاقة بين الأوساط الأكاديمية وقطاع الأعمال من خلال المنتديات العلمية والمؤتمرات البحثية.',
    benefit: 'Connects local universities and educational centers with international peers and aligns research outcomes with global labor market needs.',
    benefitAr: 'ربط الجامعات والمراكز التعليمية المحلية بنظيراتها الدولية، ومواءمة مخرجات البحث العلمي مع متطلبات سوق العمل الدولي عبر منصات التبادل الأكاديمي.',
    registrationIntro: 'For inquiries about a scientific conference, academic forum, or institutional collaboration between universities and research centers, please complete the form below.',
    registrationIntroAr: 'للتواصل حول مؤتمر علمي أو منتدى أكاديمي أو تعاون مؤسسي بين الجامعات والمراكز البحثية، يمكنكم تعبئة النموذج التالي.',
    accent: '#4338ca',
  },
]

const slugAliases: Record<string, SectorContentEntry['key']> = {
  medical: 'medical',
  'medical-healthcare': 'medical',
  healthcare: 'medical',
  health: 'medical',
  industrie: 'industrie',
  industrial: 'industrie',
  commercial: 'industrie',
  'commercial-industrial': 'industrie',
  'industrial-commercial': 'industrie',
  technology: 'technology',
  tech: 'technology',
  education: 'academia',
  academia: 'academia',
  academic: 'academia',
}

function normalize(value: string | null | undefined) {
  return (value || '').trim().toLowerCase()
}

export function getSectorContent(input: Pick<SectorRow, 'slug' | 'name' | 'name_ar'> | string) {
  const raw =
    typeof input === 'string'
      ? input
      : [input.slug, input.name, input.name_ar].filter(Boolean).map(normalize).join(' ')

  const matchedKey = Object.entries(slugAliases).find(([alias]) => raw.includes(alias))?.[1]
  return sectorEntries.find((entry) => entry.key === matchedKey) || null
}

export function getSectorRegistrationFallback(): FormField[] {
  return [
    {
      id: 'company_name',
      label_en: 'Company Name',
      label_ar: 'اسم الشركة',
      type: 'text',
      required: true,
      description_en: 'Enter the details exactly as shown in the official documents.',
      description_ar: 'يجب ادخل البيانات نفس الوثائق الرسمية.',
      width: 'half',
    },
    {
      id: 'company_specialization',
      label_en: 'Company Specialization',
      label_ar: 'تخصص الشركة',
      type: 'text',
      required: false,
      description_en: 'Enter the company specialization or field of work.',
      description_ar: 'أدخل تخصص الشركة أو مجال عملها.',
      placeholder_en: 'Company specialization',
      placeholder_ar: 'تخصص الشركة',
      width: 'half',
    },
    {
      id: 'zip_code',
      label_en: 'ZIP Code',
      label_ar: 'الرمز البريدي',
      type: 'text',
      required: true,
      width: 'half',
    },
    {
      id: 'city',
      label_en: 'City',
      label_ar: 'المدينة',
      type: 'text',
      required: true,
      width: 'half',
    },
    {
      id: 'country',
      label_en: 'Country',
      label_ar: 'الدولة',
      type: 'text',
      required: true,
      width: 'half',
    },
    {
      id: 'telephone',
      label_en: 'Company Telephone',
      label_ar: 'هاتف الشركة',
      type: 'text',
      required: false,
      width: 'half',
    },
    {
      id: 'email',
      label_en: 'Company E-Mail',
      label_ar: 'البريد الإلكتروني للشركة',
      type: 'email',
      required: false,
      width: 'half',
      description_en: 'We will not follow up on email addresses other than the company domain.',
      description_ar: 'لن تتم المتابعة مع عناوين البريد الإلكتروني التي لا تستخدم نطاق الشركة.',
    },
    {
      id: 'company_website',
      label_en: 'Company Website',
      label_ar: 'الموقع الإلكتروني للشركة',
      type: 'text',
      required: false,
      width: 'half',
    },
    {
      id: 'position_in_company',
      label_en: 'Position in the Company',
      label_ar: 'المنصب في الشركة',
      type: 'text',
      required: true,
      description_en: 'Enter the details exactly as shown in the official documents.',
      description_ar: 'يجب ادخل البيانات نفس الوثائق الرسمية.',
      width: 'half',
    },
    {
      id: 'company_registration_number',
      label_en: 'Registration Number of the Company',
      label_ar: 'رقم تسجيل الشركة',
      type: 'text',
      required: false,
      width: 'half',
      description_en: 'At the Chamber of Commerce or similar organization.',
      description_ar: 'في غرفة التجارة أو جهة مماثلة.',
    },
    {
      id: 'full_name',
      label_en: 'Full Name',
      label_ar: 'الاسم الكامل',
      type: 'text',
      required: true,
      width: 'half',
      description_en: 'Enter the full name exactly as it appears in the passport.',
      description_ar: 'أدخل الاسم الكامل كما هو مكتوب في الجواز أو الباسبور.',
      placeholder_en: 'Full name as shown in passport',
      placeholder_ar: 'الاسم الكامل كما هو مكتوب في الجواز أو الباسبور',
    },
    {
      id: 'surname',
      label_en: 'Surname',
      label_ar: 'اللقب',
      type: 'text',
      required: false,
      width: 'half',
      placeholder_en: 'Surname as shown in passport',
      placeholder_ar: 'اللقب كما هو مكتوب في الجواز أو الباسبور',
    },
    {
      id: 'sex',
      label_en: 'Sex',
      label_ar: 'الجنس',
      type: 'select',
      required: true,
      width: 'half',
      options: ['Male', 'Female'],
      options_ar: ['ذكر', 'أنثى'],
    },
    {
      id: 'civil_status',
      label_en: 'Civil Status',
      label_ar: 'الحالة الاجتماعية',
      type: 'select',
      required: false,
      width: 'half',
      options: ['Single', 'Married', 'Registered partnership', 'Separated', 'Divorced', 'Widow(er)', 'Other'],
      options_ar: ['أعزب', 'متزوج', 'شراكة مسجلة', 'منفصل', 'مطلق', 'أرمل', 'أخرى'],
    },
    {
      id: 'date_of_birth',
      label_en: 'Date of Birth',
      label_ar: 'تاريخ الميلاد',
      type: 'date',
      required: true,
      width: 'half',
    },
    {
      id: 'nationality',
      label_en: 'Nationality',
      label_ar: 'الجنسية',
      type: 'text',
      required: true,
      width: 'half',
    },
    {
      id: 'personal_telephone',
      label_en: 'Personal Telephone',
      label_ar: 'الهاتف الشخصي',
      type: 'text',
      required: true,
      width: 'half',
    },
    {
      id: 'personal_email_address',
      label_en: 'Personal E-Mail',
      label_ar: 'البريد الإلكتروني الشخصي',
      type: 'email',
      required: true,
      width: 'half',
    },
    {
      id: 'personal_home_address',
      label_en: 'Home Address',
      label_ar: 'عنوان السكن',
      type: 'textarea',
      required: false,
      placeholder_en: 'Country, governorate, district, and area',
      placeholder_ar: 'بلد و المحافظة و قضاء و منطقة',
      width: 'full',
    },
    {
      id: 'type_of_travel_document',
      label_en: 'Type of Travel Document',
      label_ar: 'نوع وثيقة السفر',
      type: 'select',
      required: true,
      width: 'half',
      options: ['Ordinary passport', 'Diplomatic passport', 'Service passport', 'Official passport', 'Special passport', 'Other travel document'],
      options_ar: ['جواز عادي', 'جواز دبلوماسي', 'جواز خدمة', 'جواز رسمي', 'جواز خاص', 'وثيقة سفر أخرى'],
    },
    {
      id: 'number_of_travel_document',
      label_en: 'Number of Travel Document',
      label_ar: 'رقم وثيقة السفر',
      type: 'text',
      required: true,
      width: 'half',
    },
    {
      id: 'date_of_issue',
      label_en: 'Date of Issue',
      label_ar: 'تاريخ الإصدار',
      type: 'date',
      required: true,
      width: 'half',
    },
    {
      id: 'date_of_expiry',
      label_en: 'Date of Expiry',
      label_ar: 'تاريخ الانتهاء',
      type: 'date',
      required: true,
      width: 'half',
    },
    {
      id: 'issuing_authority',
      label_en: 'Issuing Authority',
      label_ar: 'جهة الإصدار',
      type: 'text',
      required: true,
      width: 'half',
      placeholder_en: 'Enter issuing authority...',
      placeholder_ar: 'أدخل جهة الإصدار...',
    },
    {
      id: 'issued_by_country',
      label_en: 'Place of Birth',
      label_ar: 'محل الميلاد',
      type: 'text',
      required: true,
      width: 'half',
      placeholder_en: 'Enter place of birth...',
      placeholder_ar: 'أدخل محل الميلاد...',
    },
    {
      id: 'residence_in_other_country',
      label_en: 'Residence in a Country Other Than Current Nationality',
      label_ar: 'إقامة في دولة غير دولة الجنسية الحالية',
      type: 'select',
      required: false,
      width: 'full',
      options: ['No', 'Yes'],
      options_ar: ['لا', 'نعم'],
    },
    {
      id: 'residence_permit_number',
      label_en: 'Residence Permit or Equivalent Number',
      label_ar: 'رقم تصريح الإقامة أو ما يعادله',
      type: 'text',
      required: false,
      width: 'half',
    },
    {
      id: 'residence_permit_country',
      label_en: 'Country',
      label_ar: 'الدولة',
      type: 'text',
      required: false,
      width: 'half',
      placeholder_en: 'Enter country...',
      placeholder_ar: 'أدخل الدولة...',
    },
    {
      id: 'residence_permit_issue_date',
      label_en: 'Residence Permit Issue Date',
      label_ar: 'تاريخ الإصدار',
      type: 'date',
      required: false,
      width: 'half',
    },
    {
      id: 'residence_permit_valid_until',
      label_en: 'Residence Permit Expiry Date',
      label_ar: 'تاريخ النفاذ',
      type: 'date',
      required: false,
      width: 'half',
    },
    {
      id: 'additional_residence_in_other_country',
      label_en: 'Do You Hold Another Residence Permit?',
      label_ar: 'هل لديكم إقامة أخرى أيضًا؟',
      type: 'select',
      required: false,
      width: 'full',
      options: ['No', 'Yes'],
      options_ar: ['لا', 'نعم'],
    },
    {
      id: 'secondary_residence_permit_number',
      label_en: 'Second Residence Permit or Equivalent Number',
      label_ar: 'رقم تصريح الإقامة الأخرى أو ما يعادله',
      type: 'text',
      required: false,
      width: 'half',
    },
    {
      id: 'secondary_residence_permit_country',
      label_en: 'Second Residence Country',
      label_ar: 'دولة الإقامة الأخرى',
      type: 'text',
      required: false,
      width: 'half',
      placeholder_en: 'Enter second residence country...',
      placeholder_ar: 'أدخل دولة الإقامة الأخرى...',
    },
    {
      id: 'secondary_residence_permit_issue_date',
      label_en: 'Second Residence Permit Issue Date',
      label_ar: 'تاريخ إصدار الإقامة الأخرى',
      type: 'date',
      required: false,
      width: 'half',
    },
    {
      id: 'secondary_residence_permit_valid_until',
      label_en: 'Second Residence Permit Expiry Date',
      label_ar: 'تاريخ نفاذ الإقامة الأخرى',
      type: 'date',
      required: false,
      width: 'half',
    },
    {
      id: 'fingerprints_collected_previously',
      label_en: 'Do You Have a Previous Visa?',
      label_ar: 'هل لديك فيزا سابقة؟',
      type: 'select',
      required: false,
      width: 'full',
      options: ['No', 'Yes'],
      options_ar: ['لا', 'نعم'],
    },
    {
      id: 'previous_visa_issue_date',
      label_en: 'Previous Visa Issue Date',
      label_ar: 'تاريخ إصدار التأشيرة السابقة',
      type: 'date',
      required: false,
      width: 'half',
    },
    {
      id: 'previous_visa_valid_until',
      label_en: 'Previous Visa Expiry Date',
      label_ar: 'تاريخ نفاذ التأشيرة السابقة',
      type: 'date',
      required: false,
      width: 'half',
    },
    {
      id: 'previous_visa_number_if_known',
      label_en: 'Previous Visa Number (If Known)',
      label_ar: 'رقم التأشيرة السابقة إن وجد',
      type: 'text',
      required: false,
      width: 'half',
    },
    {
      id: 'previous_visa_source_country',
      label_en: 'Source Country',
      label_ar: 'دولة المصدر',
      type: 'text',
      required: false,
      width: 'half',
      placeholder_en: 'Enter source country...',
      placeholder_ar: 'أدخل دولة المصدر...',
    },
    {
      id: 'additional_previous_visa',
      label_en: 'Do You Have Another Previous Visa?',
      label_ar: 'هل لديكم فيزا سابقة أخرى أيضًا؟',
      type: 'select',
      required: false,
      width: 'full',
      options: ['No', 'Yes'],
      options_ar: ['لا', 'نعم'],
    },
    {
      id: 'secondary_previous_visa_issue_date',
      label_en: 'Second Previous Visa Issue Date',
      label_ar: 'تاريخ إصدار الفيزا السابقة الأخرى',
      type: 'date',
      required: false,
      width: 'half',
    },
    {
      id: 'secondary_previous_visa_valid_until',
      label_en: 'Second Previous Visa Expiry Date',
      label_ar: 'تاريخ نفاذ الفيزا السابقة الأخرى',
      type: 'date',
      required: false,
      width: 'half',
    },
    {
      id: 'secondary_previous_visa_number_if_known',
      label_en: 'Second Previous Visa Number (If Known)',
      label_ar: 'رقم الفيزا السابقة الأخرى إن وجد',
      type: 'text',
      required: false,
      width: 'half',
    },
    {
      id: 'secondary_previous_visa_source_country',
      label_en: 'Second Previous Visa Source Country',
      label_ar: 'دولة مصدر الفيزا السابقة الأخرى',
      type: 'text',
      required: false,
      width: 'half',
      placeholder_en: 'Enter second previous visa source country...',
      placeholder_ar: 'أدخل دولة مصدر الفيزا السابقة الأخرى...',
    },
  ]
}

export function mergeSectorWithContent<T extends SectorRow>(sector: T) {
  const content = getSectorContent(sector)

  if (!content) return sector

  return {
    ...sector,
    name: content.name,
    name_ar: content.nameAr,
    description: content.shortDescription,
    description_ar: content.shortDescriptionAr,
    color: sector.color || content.accent,
    sort_order: sector.sort_order ?? content.order,
  }
}

export const sectorContentList = sectorEntries
