'use client'

/* eslint-disable @typescript-eslint/no-explicit-any */

import Link from 'next/link'
import { useState } from 'react'
import { ArrowRight, BriefcaseBusiness, Building2, CalendarClock, Edit3, Mail, MapPin, Phone, ShieldCheck, UserRound } from 'lucide-react'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { cn } from '@/lib/utils'
import { APPLICATION_STEPS, getCustomerStatus, getInitials, getMissingDocuments, getProgress } from '../customer-utils'

export function CustomerDetails({ customer, registrations, appointments, edits }: { customer: any; registrations: any[]; appointments: any[]; edits: any[] }) {
  const complete = Boolean(customer.phone && customer.employer_name && customer.job_title && customer.nationality)
  const [editing, setEditing] = useState(false)
  const [saving, setSaving] = useState(false)
  const [saveError, setSaveError] = useState('')
  const [form, setForm] = useState<Record<string, string>>({
    full_name_as_passport: customer.full_name_as_passport || '', sex: customer.sex || '', nationality: customer.nationality || '', city: customer.city || '',
    phone: customer.phone || '', whatsapp_number: customer.whatsapp_number || '', email: customer.email || '', full_address: customer.full_address || '',
    employer_name: customer.employer_name || '', job_title: customer.job_title || '', department: customer.department || '', workplace_type: customer.workplace_type || '',
    work_address: customer.work_address || '', work_phone: customer.work_phone || '', source_event_name: customer.source_event_name || '', jaz_sector: customer.jaz_sector || '', preferred_contact_method: customer.preferred_contact_method || '', imported_source_date: customer.imported_source_date || '', imported_employee_name: customer.imported_employee_name || '', referred_by: customer.referred_by || '', inquiry_reason: customer.inquiry_reason || '', follow_up_date: customer.follow_up_date || '', source_note: customer.source_note || '', notes: customer.notes || '',
  })
  const updateField = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }))
  const saveProfile = async () => {
    setSaving(true); setSaveError('')
    const response = await fetch(`/api/customers/${customer.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) })
    if (!response.ok) { const result = await response.json().catch(() => null); setSaveError(result?.error || 'Could not save changes'); setSaving(false); return }
    window.location.reload()
  }
  return <div dir="ltr" lang="en" className="space-y-6">
    <Link href="/dashboard/customers" className="inline-flex items-center gap-2 text-sm text-[var(--jaz-muted)] hover:text-[var(--jaz-sovereign)]"><ArrowRight className="size-4" /> Back to customer directory</Link>
    <header className="flex flex-wrap items-start justify-between gap-5 rounded-lg border border-slate-200/80 bg-white px-5 py-5">
      <div className="flex items-center gap-4"><Avatar size="lg" title={customer.full_name_as_passport}><AvatarImage src={customer.avatar_url || undefined} alt="" /><AvatarFallback className="bg-[var(--jaz-surface-2)] text-[var(--jaz-ink)]">{getInitials(customer.full_name_as_passport)}</AvatarFallback></Avatar><div><p className="jaz-meta mb-2">Customer profile · {customer.id.slice(0, 8).toUpperCase()}</p><h1 className="text-3xl font-bold text-[var(--jaz-ink)]">{customer.full_name_as_passport}</h1><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-[var(--jaz-muted)]"><span className="flex items-center gap-1.5"><Phone className="size-3.5" />{customer.phone || 'Phone not recorded'}</span><span className="flex items-center gap-1.5"><Mail className="size-3.5" />{customer.email || 'Email not recorded'}</span></div></div></div>
      <div className="flex flex-wrap items-center gap-2"><span className={cn('rounded-full px-3 py-1.5 text-xs font-medium', complete ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700')}>{complete ? 'Complete data' : 'Needs update'}</span><button type="button" onClick={() => setEditing((value) => !value)} className="inline-flex h-9 items-center gap-2 rounded-md border border-slate-200 bg-white px-3 text-xs font-semibold text-[var(--jaz-ink)] hover:bg-slate-50"><Edit3 className="size-3.5" /> {editing ? 'Close editor' : 'Edit profile'}</button></div>
    </header>

    {editing && <section className="rounded-lg border border-red-100 bg-red-50/40 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold text-[var(--jaz-ink)]">Edit customer profile</h2><p className="mt-1 text-xs text-[var(--jaz-muted)]">Changes are saved to the customer record, not to an application.</p></div><button type="button" onClick={saveProfile} disabled={saving} className="h-9 rounded-md bg-[#8B0000] px-4 text-xs font-semibold text-white disabled:opacity-60">{saving ? 'Saving...' : 'Save changes'}</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[['full_name_as_passport', 'Full name'], ['sex', 'Gender'], ['nationality', 'Nationality'], ['city', 'City'], ['phone', 'Primary phone'], ['whatsapp_number', 'WhatsApp number'], ['email', 'Email'], ['employer_name', 'Company or organization'], ['job_title', 'Job title'], ['department', 'Department'], ['workplace_type', 'Organization type'], ['work_phone', 'Work phone'], ['work_address', 'Company address'], ['source_event_name', 'Source event'], ['jaz_sector', 'JAZ sector'], ['preferred_contact_method', 'Contact method'], ['imported_source_date', 'Source date'], ['imported_employee_name', 'Added by'], ['referred_by', 'Referred by'], ['inquiry_reason', 'Inquiry reason'], ['follow_up_date', 'Follow-up date'], ['source_note', 'Source note']].map(([key, label]) => <label key={key} className="text-xs font-medium text-[var(--jaz-muted)]">{label}<input value={form[key] || ''} onChange={(event) => updateField(key, event.target.value)} className="mt-1.5 h-9 w-full rounded-md border border-slate-200 bg-white px-3 text-sm font-normal text-[var(--jaz-ink)] outline-none focus:border-[#8B0000]" /></label>)}</div>{saveError && <p className="mt-4 text-xs font-medium text-red-700">{saveError}</p>}</section>}

    <section className="grid gap-4 lg:grid-cols-[1.45fr_1fr]">
      <ProfileSection title="Basic information" icon={UserRound}><div className="grid gap-x-6 gap-y-5 sm:grid-cols-2"><Field label="Full name in Arabic" value={customer.full_name_as_passport} /><Field label="Full name in English" value={customer.full_name_as_passport} /><Field label="Gender" value={customer.sex} /><Field label="Nationality" value={customer.nationality} /><Field label="Governorate / city" value={[customer.work_governorate, customer.city].filter(Boolean).join(' · ')} /><Field label="Client ID" value={customer.id} mono /></div></ProfileSection>
      <ProfileSection title="Contact details" icon={Phone}><div className="space-y-5"><Field label="Primary phone" value={customer.phone} /><Field label="WhatsApp number" value={customer.whatsapp_number} /><Field label="Email address" value={customer.email} /><Field label="Address" value={customer.full_address} /></div></ProfileSection>
    </section>

    <section className="grid gap-4 lg:grid-cols-[1.45fr_1fr]">
      <ProfileSection title="Professional information" icon={BriefcaseBusiness}><div className="grid gap-x-6 gap-y-5 sm:grid-cols-2"><Field label="Company or organization" value={customer.employer_name} /><Field label="Job title" value={customer.job_title} /><Field label="Department" value={customer.department} /><Field label="Organization type" value={customer.workplace_type} /><Field label="Company address" value={[customer.work_governorate, customer.work_city, customer.work_address].filter(Boolean).join(' · ')} /><Field label="Work phone" value={customer.work_phone} /></div></ProfileSection>
      <ProfileSection title="Customer status" icon={ShieldCheck}><div className="space-y-4"><div><p className="mb-2 text-xs text-[var(--jaz-muted)]">Current status</p><span className="inline-flex rounded-full bg-slate-100 px-3 py-1.5 text-xs font-medium text-slate-700">Not set yet</span></div><Field label="Last status change" value="Not recorded" /><Field label="Assigned employee" value="Not assigned" /><div><p className="mb-2 text-xs text-[var(--jaz-muted)]">Customer importance</p><span className="inline-flex rounded-full bg-[var(--jaz-surface-2)] px-3 py-1.5 text-xs text-[var(--jaz-muted)]">Standard</span></div></div></ProfileSection>
    </section>

    <section className="grid gap-4 lg:grid-cols-2"><ProfileSection title="Relationship with JAZ" icon={Building2}><div className="grid gap-x-6 gap-y-5 sm:grid-cols-2"><Field label="Source event" value={customer.source_event_name} /><Field label="JAZ sector" value={customer.jaz_sector} /><Field label="Preferred contact method" value={customer.preferred_contact_method} /><Field label="Added by" value={customer.imported_employee_name} /><Field label="Source date" value={customer.imported_source_date} /><Field label="Referred by" value={customer.referred_by} /><Field label="Inquiry reason" value={customer.inquiry_reason} /><Field label="Follow-up date" value={customer.follow_up_date} /><Field label="Added on" value={customer.created_at ? new Date(customer.created_at).toLocaleDateString('en-GB') : null} /><Field label="Last contact" value={customer.updated_at ? new Date(customer.updated_at).toLocaleDateString('en-GB') : null} /></div></ProfileSection><ProfileSection title="Interests and notes" icon={MapPin}><Field label="Interested sector" value={customer.jaz_sector} /><Field label="Source note" value={customer.source_note} multiline /><Field label="General notes" value={customer.notes} multiline /></ProfileSection></section>

    <section className="overflow-hidden rounded-lg border border-slate-200/80 bg-white"><div className="flex items-center justify-between border-b border-slate-200/80 bg-slate-50/70 px-4 py-4"><div><h2 className="font-semibold text-[var(--jaz-ink)]">Linked applications</h2><p className="mt-1 text-xs text-[var(--jaz-muted)]">A reference for current and historical applications. The customer profile remains independent.</p></div><span className="rounded-full bg-white px-2.5 py-1 text-xs text-[var(--jaz-muted)]">{registrations.length} applications</span></div><div className="divide-y divide-slate-200/70">{registrations.length ? registrations.map((registration) => <div key={registration.id} className="grid gap-3 px-4 py-4 md:grid-cols-[1.5fr_1fr_1fr_auto] md:items-center"><div><Link href={`/dashboard/participation-cases/${registration.id}`} className="font-semibold text-[var(--jaz-ink)] hover:text-[var(--jaz-sovereign)]">{registration.events?.title_ar || registration.events?.title || 'Participation application'}</Link><p className="mt-1 text-xs text-[var(--jaz-muted)]">{registration.case_number || 'No case number'}</p></div><div><div className="flex items-center gap-2"><div className="h-1.5 w-20 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-[#8B0000]" style={{ width: `${getProgress(registration)}%` }} /></div><span className="text-xs font-semibold">{getProgress(registration)}%</span></div><p className="mt-1 text-[11px] text-[var(--jaz-muted)]">Step {registration.current_step || 0} of {APPLICATION_STEPS}</p></div><div><Status registration={registration} /><p className="mt-1 text-[11px] text-[var(--jaz-muted)]">{getMissingDocuments(registration)} missing documents</p></div><Link href={`/dashboard/participation-cases/${registration.id}`} className="text-xs font-semibold text-[var(--jaz-sovereign)]">Open application</Link></div>) : <div className="px-4 py-10 text-center text-sm text-[var(--jaz-muted)]">No applications linked to this customer.</div>}</div></section>

    <section className="grid gap-4 lg:grid-cols-2"><MiniList title="Appointments" icon={CalendarClock}>{appointments.length ? appointments.map((appointment) => <div key={appointment.id} className="flex items-center justify-between px-4 py-3 text-sm"><span>{appointment.slot_date} · {appointment.slot_time}</span><span className="text-xs text-[var(--jaz-muted)]">{appointment.status}</span></div>) : <p className="px-4 py-8 text-sm text-[var(--jaz-muted)]">No linked appointments.</p>}</MiniList><MiniList title="Change history" icon={Edit3}>{edits.length ? edits.slice(0, 8).map((edit) => <div key={edit.id} className="px-4 py-3"><p className="text-sm text-[var(--jaz-ink)]">{edit.field_label || 'Application updated'}</p><p className="mt-1 text-xs text-[var(--jaz-muted)]">{edit.edited_by || 'Staff'} · {new Date(edit.created_at).toLocaleString('en-GB')}</p></div>) : <p className="px-4 py-8 text-sm text-[var(--jaz-muted)]">No changes recorded yet.</p>}</MiniList></section>
  </div>
}

function ProfileSection({ title, icon: Icon, children }: { title: string; icon: typeof UserRound; children: React.ReactNode }) { return <section className="rounded-lg border border-slate-200/80 bg-white p-5"><div className="mb-5 flex items-center gap-3 border-b border-slate-200/80 pb-4"><span className="flex size-8 items-center justify-center rounded-md bg-red-50"><Icon className="size-4 text-[#8B0000]" /></span><h2 className="font-semibold text-[var(--jaz-ink)]">{title}</h2></div>{children}</section> }
function Field({ label, value, mono = false, multiline = false }: { label: string; value?: string | null; mono?: boolean; multiline?: boolean }) { return <div className={multiline ? 'sm:col-span-2' : ''}><p className="mb-1.5 text-xs text-[var(--jaz-muted)]">{label}</p><p className={cn('text-sm font-medium', value ? 'text-[var(--jaz-ink)]' : 'text-[var(--jaz-whisper)]', mono && 'font-mono text-xs', multiline && 'min-h-12 leading-7')}>{value || 'Not recorded'}</p></div> }
function MiniList({ title, icon: Icon, children }: { title: string; icon: typeof UserRound; children: React.ReactNode }) { return <section className="overflow-hidden rounded-lg border border-slate-200/80 bg-white"><div className="flex items-center gap-3 border-b border-slate-200/80 bg-slate-50/70 px-4 py-4"><span className="flex size-8 items-center justify-center rounded-md bg-red-50"><Icon className="size-4 text-[#8B0000]" /></span><h2 className="font-semibold text-[var(--jaz-ink)]">{title}</h2></div><div className="divide-y divide-slate-200/70">{children}</div></section> }
function Status({ registration }: { registration: any }) { const label = getCustomerStatus(registration); return <span className={cn('inline-flex rounded-full px-2 py-1 text-[11px] font-medium', label === 'Completed' ? 'bg-green-50 text-green-700' : label === 'Missing documents' ? 'bg-red-50 text-red-700' : label === 'Payment pending' ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-700')}>{label === 'Completed' ? 'Completed' : label === 'Missing documents' ? 'Missing documents' : label === 'Payment pending' ? 'Payment pending' : 'In progress'}</span> }
