'use client'

/* eslint-disable @typescript-eslint/no-explicit-any */

import Link from 'next/link'
import { ArrowLeft, CalendarClock, Mail, MapPin, Phone, ShieldCheck, UserRound } from 'lucide-react'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { cn } from '@/lib/utils'
import { APPLICATION_STEPS, getCustomerStatus, getInitials, getMissingDocuments, getProgress } from '../customer-utils'

export function CustomerDetails({ customer, registrations, appointments, edits }: { customer: any; registrations: any[]; appointments: any[]; edits: any[] }) {
  return <div dir="ltr" lang="en" className="space-y-5">
    <Link href="/dashboard/customers" className="inline-flex items-center gap-2 text-sm text-[var(--jaz-muted)] hover:text-[var(--jaz-sovereign)]"><ArrowLeft className="size-4" /> Back to Customers</Link>
    <header className="flex flex-wrap items-start justify-between gap-4 border-b border-[var(--jaz-line)] pb-4">
      <div className="flex items-center gap-3"><Avatar size="lg" title={customer.full_name_as_passport}><AvatarImage src={customer.avatar_url || undefined} alt="" /><AvatarFallback className="bg-[var(--jaz-surface-2)] text-[var(--jaz-ink)]">{getInitials(customer.full_name_as_passport)}</AvatarFallback></Avatar><div><p className="jaz-meta">Customer profile</p><h1 className="mt-1 text-2xl font-bold text-[var(--jaz-ink)]">{customer.full_name_as_passport}</h1><div className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-xs text-[var(--jaz-muted)]"><span className="flex items-center gap-1"><Phone className="size-3" />{customer.phone || customer.whatsapp_number || 'No phone'}</span><span className="flex items-center gap-1"><Mail className="size-3" />{customer.email || 'No email'}</span></div></div></div>
      <div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-[var(--jaz-surface-2)] px-2.5 py-1 text-[var(--jaz-muted)]">{registrations.length} applications</span><span className="rounded-full bg-[var(--jaz-surface-2)] px-2.5 py-1 text-[var(--jaz-muted)]">Updated {new Date(customer.updated_at).toLocaleDateString('en-GB')}</span></div>
    </header>

    <section className="grid gap-3 md:grid-cols-3"><Info label="Passport" value={customer.passport_number || 'Not provided'} icon={ShieldCheck} /><Info label="Nationality / residence" value={[customer.nationality, customer.residence_country].filter(Boolean).join(' · ') || 'Not provided'} icon={MapPin} /><Info label="Profession" value={[customer.job_title, customer.employer_name].filter(Boolean).join(' · ') || 'Not provided'} icon={UserRound} /></section>

    <section className="overflow-hidden rounded-lg border border-[var(--jaz-line)] bg-white"><div className="border-b border-[var(--jaz-line)] px-4 py-3"><h2 className="font-semibold text-[var(--jaz-ink)]">Applications</h2><p className="mt-0.5 text-xs text-[var(--jaz-muted)]">Every active and historical application linked to this customer.</p></div><div className="divide-y divide-[var(--jaz-line)]">{registrations.length ? registrations.map((registration) => <div key={registration.id} className="grid gap-3 px-4 py-3 md:grid-cols-[1.5fr_1fr_1fr_1fr_auto] md:items-center"><div><Link href={`/dashboard/participation-cases/${registration.id}`} className="font-semibold text-[var(--jaz-ink)] hover:text-[var(--jaz-sovereign)]">{registration.events?.title_ar || registration.events?.title || 'Application'}</Link><p className="mt-0.5 text-xs text-[var(--jaz-muted)]">{registration.case_number || 'No case number'}</p></div><div><div className="flex items-center gap-2"><div className="h-1.5 w-20 overflow-hidden rounded-full bg-[var(--jaz-line)]"><div className="h-full bg-[var(--jaz-sovereign)]" style={{ width: `${getProgress(registration)}%` }} /></div><span className="text-xs font-semibold">{getProgress(registration)}%</span></div><p className="mt-1 text-[11px] text-[var(--jaz-muted)]">Step {registration.current_step || 0} of {APPLICATION_STEPS}</p></div><div><Status registration={registration} /><p className="mt-1 text-[11px] text-[var(--jaz-muted)]">{getMissingDocuments(registration)} missing documents</p></div><div className="text-xs text-[var(--jaz-muted)]">{registration.assigned_employee?.full_name || 'Unassigned'}</div><Link href={`/dashboard/participation-cases/${registration.id}`} className="text-xs font-semibold text-[var(--jaz-sovereign)]">Open</Link></div>) : <div className="px-4 py-10 text-center text-sm text-[var(--jaz-muted)]">No applications linked to this customer.</div>}</div></section>

    <section className="grid gap-5 lg:grid-cols-2"><section className="rounded-lg border border-[var(--jaz-line)] bg-white"><div className="border-b border-[var(--jaz-line)] px-4 py-3"><h2 className="font-semibold text-[var(--jaz-ink)]">Appointments</h2></div><div className="divide-y divide-[var(--jaz-line)]">{appointments.length ? appointments.map((appointment) => <div key={appointment.id} className="flex items-center justify-between px-4 py-3 text-sm"><span className="flex items-center gap-2"><CalendarClock className="size-4 text-[var(--jaz-muted)]" />{appointment.slot_date} · {appointment.slot_time}</span><span className="text-xs text-[var(--jaz-muted)]">{appointment.status}</span></div>) : <p className="px-4 py-8 text-sm text-[var(--jaz-muted)]">No appointments linked yet.</p>}</div></section><section className="rounded-lg border border-[var(--jaz-line)] bg-white"><div className="border-b border-[var(--jaz-line)] px-4 py-3"><h2 className="font-semibold text-[var(--jaz-ink)]">Important activity</h2></div><div className="divide-y divide-[var(--jaz-line)]">{edits.length ? edits.slice(0, 8).map((edit) => <div key={edit.id} className="px-4 py-3"><p className="text-sm text-[var(--jaz-ink)]">{edit.field_label || 'Application updated'}</p><p className="mt-0.5 text-xs text-[var(--jaz-muted)]">{edit.edited_by || 'Staff'} · {new Date(edit.created_at).toLocaleString('en-GB')}</p></div>) : <p className="px-4 py-8 text-sm text-[var(--jaz-muted)]">No important activity recorded.</p>}</div></section></section>
  </div>
}

function Info({ label, value, icon: Icon }: { label: string; value: string; icon: typeof UserRound }) { return <div className="flex items-center gap-3 rounded-lg border border-[var(--jaz-line)] bg-white px-4 py-3"><Icon className="size-4 text-[var(--jaz-sovereign)]" /><div><p className="text-[11px] text-[var(--jaz-muted)]">{label}</p><p className="mt-0.5 text-sm font-medium text-[var(--jaz-ink)]">{value}</p></div></div> }
function Status({ registration }: { registration: any }) { const label = getCustomerStatus(registration); return <span className={cn('inline-flex rounded-full px-2 py-1 text-[11px] font-medium', label === 'Completed' ? 'bg-green-50 text-green-700' : label === 'Missing documents' ? 'bg-red-50 text-red-700' : label === 'Payment pending' ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-700')}>{label}</span> }
